development:
  adapter: postgresql
  database: ProyectRuby_development

test:
  adapter: postgresql
  database: ProyectRuby_test

production:
  adapter: postgresql
  database: ProyectRuby_production
  url: <%= ENV.fetch("DATABASE_URL") %>
